on:
  workflow_dispatch: {}
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: |
        apk add openjdk21 # Add ecosystem specific installs here
        semgrep ci --allow-local-builds --verbose --supply-chain
